Structure
```
0x05-python-exceptions/           # Main directory for this project
   ├── 0-safe_print_list.py          # Task 0: Safe list printing
   ├── 1-safe_print_integer.py       # Task 1: Safe printing of an integer
   ├── 2-safe_print_list_integers.py # Task 2: Print and count integers
   ├── 3-safe_print_division.py      # Task 3: Integer division with debug
   ├── 4-list_division.py            # Task 4: Divide element by element of two lists
   ├── 5-raise_exception.py          # Task 5: Raise a type exception
   ├── 6-raise_exception_msg.py      # Task 6: Raise a name exception with a message
   ├── 100-safe_print_integer_err.py # Task 7: Safe integer print with error message
   ├── 101-safe_function.py          # Task 8: Safe function execution
   ├── 102-magic_calculation.py      # Task 9: ByteCode -> Python
   ├── 103-python.c                  # Task 10: CPython #2: PyFloatObject
   ├── README.md                     # Project's README file
   └── tests/                        # Subdirectory for test files
       ├── 0-main.py                 # Test for Task 0
       ├── 1-main.py                 # Test for Task 1
       ├── 2-main.py                 # Test for Task 2
       ├── 3-main.py                 # Test for Task 3
       ├── 4-main.py                 # Test for Task 4
       ├── 5-main.py                 # Test for Task 5
       ├── 6-main.py                 # Test for Task 6
       ├── 100-main.py               # Test for Task 7
       ├── 101-main.py               # Test for Task 8
       ├── 102-main.py               # Test for Task 9
       ├── 103-tests.py              # Test for Task 10
```
